#!/bin/bash

# APK Optimizer Tool v.0.1
# Author - Findlee
# E-Mail - thefindlee@gmail.com
# Profile on 4pda.ru - http://4pda.ru/forum/index.php?showuser=1498763

chmod 777 tools

while :
do

setterm -bold 
tput setaf 1 
clear
echo "============================================================="
echo "APK Optimizer Tool by Findlee v.0.1"
echo "============================================================="
tput sgr0

echo "
1)Deodex app and framework
2)Zipalign app folder
3)Optimize png images in apk files
4)CleanUp
5)Exit
"

read -p "Option: " opt
echo ""
case $opt in

1)
# Deodex app
if [[ ! -d app ]]
then
echo "App folder not found! Exiting..."
exit 0
fi
if [[ ! -d framework ]]
then
echo "Framework folder not found! Exiting..."
exit 0
fi
echo "Enter number API (Only number)"
setterm -bold 
tput setaf 1
echo "Android 2.1 Eclair (API level 7)
Android 2.2–2.2.3 Froyo (API level 8) 
Android 2.3–2.3.2 Gingerbread (API level 9)
Android 2.3.3–2.3.7 Gingerbread (API level 10)
Android 3.0 Honeycomb (API level 11)
Android 3.1 Honeycomb (API level 12)
Android 3.2 Honeycomb (API level 13)
Android 4.0–4.0.2 Ice Cream Sandwich (API level 14)
Android 4.0.3–4.0.4 Ice Cream Sandwich (API level 15)
Android 4.1 Jelly Bean (API level 16)
Android 4.2 Jelly Bean (API level 17)"
tput sgr0
read -p "API: " api
if [[ "$api" == "" ]]
then
echo "You not wirited API , Default 10"
api=`10`
fi
odex=`find app | grep -c ".odex"`
apk=`find app | grep -c ".apk"`
setterm -bold 
tput setaf 1 
echo "Found $odex Odex Files and $apk APK Files"
tput sgr0
if
[[ "$odex" == "0" ]]
then
echo ".odex files not found! Exiting..."
exit 0
fi
if
[[ "$apk" == "0" ]]
then
echo ".apk not found! Exiting..."
exit 0
fi
cp tools/baksmali.jar tools/smali.jar app
cd app
odexlist=`find *.odex | sed s/.odex//`
setterm -bold 
tput setaf 1 
echo "Deodexing"
tput sgr0
echo "---------"
for odexfile in $odexlist
do
java -Xmx512m -jar baksmali.jar -a $api -d ../framework -x $odexfile.odex -o $odexfile
java -Xmx512m -jar smali.jar -a $api $odexfile -o classes.dex
zip -r -q $odexfile.apk classes.dex
rm -R $odexfile $odexfile.odex classes.dex
echo "$odexfile Deodexed"
done
rm baksmali.jar smali.jar
cd ..
rm tools/*.txt
odexnew=`find app | grep -c ".odex"`
apknew=`find app | grep -c ".apk"`
echo "Found $odexnew Odex Files and $apknew APK Files"

# Deodex framework

odexfr=`find framework | grep -c ".odex"`
jar=`find framework | grep -c ".jar"`
setterm -bold 
tput setaf 1 
echo "Found $odex Odex Files and $jar JAR Files"
tput sgr0
if
[[ "$odexfr" == "0" ]]
then
echo ".odex files not found! Exiting..."
exit 0
fi
if
[[ "jar" == "0" ]]
then
echo ".apk files not found! Exiting..."
exit 0
fi
cp tools/baksmali.jar tools/smali.jar framework
cd framework
odexfrlist=`find *.odex | sed s/.odex//`
setterm -bold 
tput setaf 1 
echo "Deodexing in framework folder"
tput sgr0
echo "---------"
for odexfrfile in $odexfrlist
do
java -Xmx512m -jar baksmali.jar -a $api -d ../framework -x $odexfrfile.odex -o $odexfrfile
java -Xmx512m -jar smali.jar -a $api $odexfrfile -o classes.dex
zip -r -q $odexfrfile.jar classes.dex
rm -R $odexfrfile $odexfrfile.odex classes.dex
echo "$odexfrfile Deodexed"
done
rm baksmali.jar smali.jar
cd ..
echo "All Done"
echo "Press any key"
read
;;

2)
if [[ ! -d app ]]
then
echo "App folder not found! Exiting..."
exit 0
fi
if
[[ -d tmp/app_zipaligned ]]
then
echo "Deleting old app_zipaligned folder"
rm -R tmp/app_zipaligned
fi
mkdir -p tmp/app_zipaligned
cd app
zipapk=`find *.apk`
setterm -bold 
tput setaf 1 
echo "Zipaligning"
tput sgr0
echo "-----------"
for zipaligning in $zipapk
do
../tools/zipalign 4 $zipaligning ../tmp/app_zipaligned/$zipaligning
echo $zipaligning zipaligned
done
cd ..
rm -R app
mv tmp/app_zipaligned app
rm -R tmp
setterm -bold 
tput setaf 1
echo "All Done"
echo "Press any key"
tput sgr0
read
;;
3)
if [[ ! -d app ]]
then
echo "App folder not found! Exiting..."
exit 0
fi
cd app
optiapk=`find *.apk | sed s/.apk//`
setterm -bold 
tput setaf 1
echo "Choose Compression (1-7)"
read compression
echo "Optimizing APK"
echo "--------------"
tput sgr0
for optimapk in $optiapk
do
unzip $optimapk.apk -d $optimapk
../tools/optipng -o$compression $optimapk/res/drawable-*/*
zip -r -q $optimapk.apk $optimapk
rm -R $optimapk
done
echo "All Done"
echo "Press any key"
read
;;
4)rm -Rf app app_zipaligned framework *.
;;
5)exit 0
esac
done
