#!/bin/bash

# APK Optimizer Tool v.2.0
# Author - Findlee
# E-Mail - thefindlee@gmail.com

if [[ ! -d tools ]] 
then echo "Error: tools folder not found" 
exit
fi

chmod -R 777 tools
mkdir -p app framework

while :
do

setterm -bold 
tput setaf 1 
clear
echo "============================================================="
echo "APK Optimizer Tool by Findlee v.2.0"
echo "============================================================="
tput sgr0

echo "
1)Deodex app and framework
2)Zipalign apk files
3)Optimize png images in apk files
4)CleanUp
5)Exit
"
read -p "Option: " opt
if [ "$?" != "1" ]
then
case $opt in
1)tools/deodex;continue;;
2)tools/zipalign-script;continue;;
3)tools/optipng-apk;continue;;
4)rm -Rf app app_zipaligned framework *. ;;
5)exit;;
esac
fi
done
