#!/bin/bash

source tools/fn

# Deodex app
if [[ ! -d app ]] || [[ ! -d framework ]]
then
setterm -bold 
tput setaf 1 
echo "App folder and Framework folder not found! Exiting..."
echo "Press any key"
tput sgr0
read
exit 1
fi
echo "Enter number API (Only number)"
api_levels
read -p "API: " api
if [[ "$api" == "" ]]
then
echo "You not wirited API , Default 10"
api=`10`
fi
odex=`find app | grep -c ".odex"`
apk=`find app | grep -c ".apk"`
setterm -bold 
tput setaf 1 
echo "Found $odex Odex Files and $apk APK Files"
if
[[ "$odex" == "0" ]]
then
echo ".odex files not found! Exiting from folder..."
fi
if
[[ "$apk" == "0" ]]
then
echo ".apk not found! Exiting from folder..."
fi
cp tools/baksmali.jar tools/smali.jar app
cd app
odexlist=`find *.odex | sed s/.odex//`
echo "Deodexing"
echo "---------"
tput sgr0
for odexfile in ${odexlist[@]}
do
java -Xmx512m -jar baksmali.jar -a $api -d ../framework -x $odexfile.odex -o $odexfile
java -Xmx512m -jar smali.jar -a $api $odexfile -o classes.dex
zip -r -q $odexfile.apk classes.dex
rm -R $odexfile $odexfile.odex classes.dex
echo "$odexfile Deodexed"
done
rm baksmali.jar smali.jar
cd ..
odexnew=`find app | grep -c ".odex"`
apknew=`find app | grep -c ".apk"`
echo "Found $odexnew Odex Files and $apknew APK Files"

# Deodex framework

odexfr=`find framework | grep -c ".odex"`
jar=`find framework | grep -c ".jar"`
setterm -bold 
tput setaf 1
echo "---------"
echo "Found $odex Odex Files and $jar JAR Files in framework folder"
if
[[ "$odexfr" == "0" ]]
then
echo ".odex files not found! Exiting..."
exit 1
fi
if
[[ "jar" == "0" ]]
then
echo ".jar files not found! Exiting..."
exit 1
fi
cp tools/baksmali.jar tools/smali.jar framework
cd framework
odexfrlist=`find *.odex | sed s/.odex//`
echo "Deodexing in framework folder"
echo "---------"
tput sgr0
for odexfrfile in $odexfrlist
do
java -Xmx512m -jar baksmali.jar -a $api -d ../framework -x $odexfrfile.odex -o $odexfrfile
java -Xmx512m -jar smali.jar -a $api $odexfrfile -o classes.dex
zip -r -q $odexfrfile.jar classes.dex
rm -R $odexfrfile $odexfrfile.odex classes.dex
echo "$odexfrfile Deodexed"
done
rm baksmali.jar smali.jar
cd ..
all_done
