#!/bin/bash

# Findlee (c) 2013
# thefindlee@gmail.com

api_levels () {
setterm -bold 
tput setaf 1
echo "Android 2.1 Eclair (API level 7)
Android 2.2–2.2.3 Froyo (API level 8) 
Android 2.3–2.3.2 Gingerbread (API level 9)
Android 2.3.3–2.3.7 Gingerbread (API level 10)
Android 3.0 Honeycomb (API level 11)
Android 3.1 Honeycomb (API level 12)
Android 3.2 Honeycomb (API level 13)
Android 4.0–4.0.2 Ice Cream Sandwich (API level 14)
Android 4.0.3–4.0.4 Ice Cream Sandwich (API level 15)
Android 4.1 Jelly Bean (API level 16)
Android 4.2 Jelly Bean (API level 17)"
tput sgr0
read -p "API: " api
}

app_deodex () {
		odex=`find app | grep -c ".odex"`
		apk=`find app | grep -c ".apk"`
		setterm -bold 
		tput setaf 1 
		echo "Found $odex Odex Files and $apk APK Files"
		if
		[[ "$odex" != "0" ]] && [[ "$apk" != "0" ]]
		then
		cp tools/baksmali.jar tools/smali.jar app
		cd app
		odexlist=`find *.odex | sed s/.odex//`
		echo "Deodexing"
		echo "---------"
		tput sgr0
		for odexfile in ${odexlist[@]}
		do
		java -jar baksmali.jar -d ../framework -a $api -x $odexfile.odex -o $odexfile
		java -jar smali.jar -a $api $odexfile -o classes.dex
		zip -r -q $odexfile.apk classes.dex
		rm -R $odexfile $odexfile.odex classes.dex
		echo "$odexfile Deodexed"
		done
		rm baksmali.jar smali.jar
		cd ..
		odexnew=`find app | grep -c ".odex"`
		apknew=`find app | grep -c ".apk"`
		echo "Found $odexnew Odex Files and $apknew APK Files"
		echo "Deodexing in app folder finished"
		else
		echo ".odex or .jar files in app folder not found"
		fi
}

framework_deodex () {
		odexfr=`find framework | grep -c ".odex"`
		jar=`find framework | grep -c ".jar"`
		setterm -bold 
		tput setaf 1
		echo "Framework Deodexing"
		echo "-------------------"
		echo "Found $odexfr .odex files and $jar .jar files in framework folder"
		if
		[[ "$odexfr" != "0" ]] && [[ "$jar" != "0" ]]
		then
		cp tools/baksmali.jar tools/smali.jar framework
		cd framework
		odexfrlist=`find *.odex | sed s/.odex//`
		echo "Deodexing in framework folder"
		echo "---------"
		tput sgr0
		for odexfrfile in ${odexfrlist[@]}
		do
		java -Xmx512m -jar baksmali.jar -a $api -d ../framework -x $odexfrfile.odex -o $odexfrfile
		java -Xmx512m -jar smali.jar -a $api $odexfrfile -o classes.dex
		zip -r -q $odexfrfile.jar classes.dex
		rm -R $odexfrfile $odexfrfile.odex classes.dex
		echo "$odexfrfile Deodexed"
		done
		rm baksmali.jar smali.jar
		cd ..
		echo "Deodexing in framework folder finished"
		else
		echo ".odex or .jar files in framework folder not found"
		fi
}

clear

while true
do

setterm -bold 
tput setaf 1 
clear
echo "============================================================="
echo "APK Deodex Tool by Findlee v.1.0"
echo "============================================================="
tput sgr0

echo "
1)Deodex app and framework
2)Deodex only app
3)Deodex only framework
4)Main Menu
"

read -p "Option: " opt
case $opt in

1)
api_levels
app_deodex
framework_deodex
;;

2)
api_levels
app_deodex
;;

3)
api_levels
framework_deodex
;;

4)./aot
;;

esac
done
