#!/bin/bash

function all_done {
setterm -bold 
tput setaf 1 
echo "Done"
echo "Press any key"
tput sgr0
read
}

function not_found {
if [[ ! -d app ]] || [[ ! -d framework ]]
then
setterm -bold 
tput setaf 1 
echo "App folder or Framework folder not found! Exiting..."
echo "Press any key"
tput sgr0
read
exit 1
fi
}

function api_levels {
setterm -bold 
tput setaf 1
echo "Android 2.1 Eclair (API level 7)
Android 2.2–2.2.3 Froyo (API level 8) 
Android 2.3–2.3.2 Gingerbread (API level 9)
Android 2.3.3–2.3.7 Gingerbread (API level 10)
Android 3.0 Honeycomb (API level 11)
Android 3.1 Honeycomb (API level 12)
Android 3.2 Honeycomb (API level 13)
Android 4.0–4.0.2 Ice Cream Sandwich (API level 14)
Android 4.0.3–4.0.4 Ice Cream Sandwich (API level 15)
Android 4.1 Jelly Bean (API level 16)
Android 4.2 Jelly Bean (API level 17)"
tput sgr0
}
