#!/bin/bash

# Findlee (c) 2013
# thefindlee@gmail.com

optiapk_app () {
echo "Choose Compression (1-7)"
read compression
apk=`find app | grep -c ".apk"`
if [[ "$apk" != "0" ]]
then
cd app
rm -Rf res
optiapk=`find *.apk | sed s/.apk//`
setterm -bold 
tput setaf 1
echo "Optimizing APK files in app folder"
echo "----------------------------------"
tput sgr0
for optimapk in ${optiapk[@]}
do
unzip $optimapk.apk -d $optimapk 1>>/dev/null
if [[ -d $optimapk/res ]]
then
cd $optimapk/res
found_png=`find . | grep .png | wc -l`
cd ../..
	if [[ "$found_png" != "0" ]]
	then
	mv $optimapk/res $PWD
	rm -Rf $optimapk
	../tools/optipng -o$compression res/drawable/* 1>/dev/null
	../tools/optipng -o$compression res/drawable-*/* 1>/dev/null
	zip -r -q $optimapk.apk res
	rm -R res
	echo "$optimapk.apk optimized"
	else
	echo "No png images in $optimapk.apk for compression"
	rm -R $optimapk
	fi
else
echo "No png images in $optimapk.apk for compression"
rm -R $optimapk
fi
done
echo "Optimizing apk files in app folder finished"
else
echo "Apk files in app folder not found"
fi
cd ..
}

optiapk_framework () {
apkfr=`find framework | grep -c ".apk"`
if [[ "$apkfr" != "0" ]]
then
echo "Optimizing .apk files in framework folder"
cd framework
rm -Rf res
optifrlist=`find *.apk | sed s/.apk//`
setterm -bold 
tput setaf 1
echo "Optimizing APK files in framework folder"
echo "----------------------------------------"
tput sgr0
for optifr in ${optifrlist[@]}
do
unzip $optifr.apk -d $optifr 1>>/dev/null
if [[ -d $optifr/res ]]
then
cd $optifr/res
found_png=`find . | grep .png | wc -l`
cd ../..
	if [[ "$found_png" != "0" ]]
	then
	mv $optifr/res $PWD
	rm -Rf $optifr
	../tools/optipng -o$compression res/drawable/* 1>/dev/null
	../tools/optipng -o$compression res/drawable-*/* 1>/dev/null
	zip -r -q $optifr.apk res
	rm -R res
	echo "$optifr.apk optimized"
	else
	echo "No png images in $optifr.apk for compression"
	rm -R $optifr
	fi
else
echo "No png images in $optifr.apk for compression"
rm -R $optifr
fi
done
echo "Optimizing apk files in framework folder finished"
else
echo "Apk files in framework folder not found"
fi
}

while true
do

setterm -bold 
tput setaf 1 
clear
echo "============================================================="
echo "OptiAPK Tool by Findlee v.1.0"
echo "============================================================="
tput sgr0

echo "
1)OptiAPK app and framework
2)OptiAPK only app
3)OptiAPK only framework
4)Main menu
"

read -p "Option: " opt
case $opt in

1)
optiapk_app
optiapk_framework
;;

2)optiapk_app
;;
3)
optiapk_framework
;;
4)./aot
;;

esac
done

