#!/bin/bash

source tools/fn
not_found
if [[ -d app ]]
then
echo "App folder found"
cd app
apklist=`find *.apk`
setterm -bold 
tput setaf 1 
echo "Zipaligning in app folder"
tput sgr0
echo "-----------"
for zipaligning in ${apklist[@]}
do
../tools/zipalign 4 $zipaligning $zipaligning-zipaligned
rm $zipaligning
mv $zipaligning-zipaligned $zipaligning
echo $zipaligning zipaligned
done
cd ..
all_done
fi
if [[ -d framework ]]
then
echo "Framework folder found"
cd framework
apkfrlist=`find *.apk`
setterm -bold 
tput setaf 1 
echo "Zipaligning in framework folder"
tput sgr0
echo "-----------"
for zipaligningfrapk in ${apkfrlist[@]}
do
../tools/zipalign 4 $zipaligningfrapk $zipaligningfrapk-zipaligned
rm $zipaligningfrapk
mv $zipaligningfrapk-zipaligned $zipaligningfrapk
echo "$zipaligningfrapk" zipaligned
done
cd ..
all_done
fi
