#!/bin/bash

# Findlee (c) 2013
# thefindlee@gmail.com

app_zipalign () {
apk=`find app | grep -c ".apk"`
if [[ "$apk" != "0" ]]
then
cd app
apklist=`find *.apk`
setterm -bold 
tput setaf 1 
echo "Zipaligning in app folder"
tput sgr0
echo "-----------"
for zipaligning in ${apklist[@]}
do
../tools/zipalign 4 $zipaligning $zipaligning-zipaligned
rm $zipaligning
mv $zipaligning-zipaligned $zipaligning
echo $zipaligning zipaligned
done
cd ..
echo "Zipaligning in app folder finished"
else
echo "Apk files in app folder not found"
fi
}

framework_zipalign () {
apkfr=`find framework | grep -c ".apk"`
jarfr=`find framework | grep -c ".jar"`
if [[ "$apkfr" != "0" ]] && [[ "$jarfr" != "0" ]]
then
cd framework
apkfrlist=`find *.apk`
setterm -bold 
tput setaf 1 
echo "Zipaligning in framework folder"
tput sgr0
echo "-----------"
for zipaligningfrapk in ${apkfrlist[@]}
do
../tools/zipalign 4 $zipaligningfrapk $zipaligningfrapk-zipaligned
rm $zipaligningfrapk
mv $zipaligningfrapk-zipaligned $zipaligningfrapk
echo "$zipaligningfrapk" zipaligned
done
cd ..
echo "Zipaligning in framework folder finished"
else
echo "Apk files in framework folder not found"
fi
}

while true
do

setterm -bold 
tput setaf 1 
clear
echo "============================================================="
echo "APK Zipalign Tool by Findlee v.1.0"
echo "============================================================="
tput sgr0

echo "
1)Zipaling app and framework
2)Zipaling only app
3)Zipalign only framework
4)Main Menu
"

read -p "Option: " opt
case $opt in

1)
app_zipalign
framework_zipalign
;;

2)
app_zipalign
;;

3)
framework_zipalign
;;

4)./aot
;;

esac
done
